config:
  environment:
    generation_length: 100
    items_list:
    - diamond
    - gold
    - apple
    - emerald
    - redstone
    max_trade_amount: 5.0
    max_trade_distance: 20.0
    mutation_rate: 0.1
    population_size: 5
    survival_rate: 0.5
    world_size: 100.0
  learning:
    learning_rate: 0.001
    matrix_update_rate: 0.1
  logging:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    level: INFO
    log_file: trading.log
  network:
    hidden_dim: 128
  server:
    debug: false
    host: 0.0.0.0
    port: 8080
  socket:
    auto_connect: true
    enabled: true
    namespace: /model
    server_url: http://localhost:3001
  training:
    early_stopping_patience: 20
    log_frequency: 10
    max_generations: 100
    model_save_frequency: 10
    model_save_path: models/trading_agents
    simulation_speed: 0.01
    target_fitness: 100.0
generation: 19
generation_stats:
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    sFWZxXZnOkA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    +0+mHoTfQkA=
  generation: 0
  total_trades: 4
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    7mjp15aHMEA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    WjcdWJdyPUA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    sNv2CNnrQkA=
  generation: 1
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    hzpVu5erNkA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    yyM9CN/eO0A=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    d5PO4sZmQ0A=
  generation: 2
  total_trades: 100
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    nrcrY+o8MEA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    r5zvAXlBNUA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AGRIX0hZRkA=
  generation: 3
  total_trades: 14
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Xm/jfT1/EMA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    nS/DGogvOEA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Ykx/4qrMQEA=
  generation: 4
  total_trades: 1
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    brA2yAA5MEA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Lh9iR2wHN0A=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    1lvscEppPEA=
  generation: 5
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    M38nWtLGM0A=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    1oMvykJVNEA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    UrvncRRRNkA=
  generation: 6
  total_trades: 6
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    G9JszdYPMEA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    RN+cZLElNkA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    H+3qc66BPUA=
  generation: 7
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    4Fr/ZmcOMUA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    nUb/LvL+NUA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    XQwDbKvBOUA=
  generation: 8
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    PrDIQxMsMEA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    BezrJNWKN0A=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    LCYaaT4OPEA=
  generation: 9
  total_trades: 22
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    skNnelHgMkA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    qSoQfzpQNEA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    k6oQOPUEO0A=
  generation: 10
  total_trades: 1
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    h03wGfMTL0A=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    M86i0KBjOUA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    5IdGdH+JSEA=
  generation: 11
  total_trades: 13
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    qHlDhT+qMEA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    cmN2T4KbNkA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    GQY17p7QPEA=
  generation: 12
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Gbaj77HmMUA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    3Vj/B1cSNkA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    9IrICfoKOUA=
  generation: 13
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    qLdoJrVUM0A=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    gs3uZXEoOUA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    ADfbrp3aPEA=
  generation: 14
  total_trades: 1
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    goKUqPZpNUA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    VnM+zxEaOEA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    GbOnBGn+O0A=
  generation: 15
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Szls253kMkA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    CLbBrnRqN0A=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    mhgiteAMQ0A=
  generation: 16
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    RDEBn/WsMUA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    DRbOrw6nPUA=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    utwZUssnQ0A=
  generation: 17
  total_trades: 1
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    dBovSwHnMkA=
- avg_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Pdpw1vDXO0A=
  best_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    7PBnxrEXQkA=
  generation: 18
  total_trades: 0
  worst_fitness: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    o/WrJk+cN0A=
timestep: 1900
